import type { PdfFieldMapping } from "../types/pdfForms";

const inspectionNote = "Update pdfFieldName after inspecting official PC-200 PDF field names.";

export const pc200Mappings: PdfFieldMapping[] = [
  {
    pdfFieldName: "Probate Court Name",
    estateHornetPath: "matter.probateCourt",
    label: "Probate court",
    fieldType: "text",
    required: true,
    reviewRequired: false,
    enabled: true,
    notes: "Confirmed from installed PC-200 AcroForm field inspection.",
  },
  {
    pdfFieldName: "Estate of",
    estateHornetPath: "matter.decedent.fullName",
    label: "Decedent full name",
    fieldType: "text",
    required: true,
    reviewRequired: false,
    enabled: true,
    notes: "Confirmed from installed PC-200 AcroForm field inspection.",
  },
  {
    pdfFieldName: "Date of Death",
    estateHornetPath: "matter.decedent.dateOfDeath",
    label: "Date of death",
    fieldType: "date",
    formatter: "date",
    required: true,
    reviewRequired: false,
    enabled: true,
    notes: "Confirmed from installed PC-200 AcroForm field inspection.",
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_DATE_OF_BIRTH",
    estateHornetPath: "matter.decedent.dateOfBirth",
    label: "Date of birth",
    fieldType: "date",
    formatter: "date",
    required: false,
    reviewRequired: false,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "Decedents Residence at Time of Death Include full address",
    estateHornetPath: "matter.decedent.address.full",
    label: "Decedent address",
    fieldType: "text",
    formatter: "fullAddress",
    required: true,
    reviewRequired: false,
    enabled: true,
    notes: "Confirmed from installed PC-200 AcroForm field inspection.",
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_DECEDENT_CITY",
    estateHornetPath: "matter.decedent.address.city",
    label: "Decedent city",
    fieldType: "text",
    required: false,
    reviewRequired: false,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_DECEDENT_STATE",
    estateHornetPath: "matter.decedent.address.state",
    label: "Decedent state",
    fieldType: "text",
    required: false,
    reviewRequired: false,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_DECEDENT_ZIP",
    estateHornetPath: "matter.decedent.address.zip",
    label: "Decedent ZIP",
    fieldType: "text",
    required: false,
    reviewRequired: false,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "Petitioner Name and address",
    estateHornetPath: "matter.fiduciary.nameAndAddress",
    label: "Petitioner/fiduciary name and address",
    fieldType: "text",
    required: true,
    reviewRequired: false,
    enabled: true,
    notes: "Confirmed from installed PC-200 AcroForm field inspection.",
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_PETITIONER_ADDRESS",
    estateHornetPath: "matter.fiduciary.address.full",
    label: "Petitioner/fiduciary address",
    fieldType: "text",
    required: true,
    reviewRequired: false,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "Phone number1",
    estateHornetPath: "matter.fiduciary.phone",
    label: "Petitioner/fiduciary phone",
    fieldType: "text",
    formatter: "phone",
    required: false,
    reviewRequired: false,
    enabled: true,
    notes: "Confirmed from installed PC-200 AcroForm field inspection.",
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_PETITIONER_EMAIL",
    estateHornetPath: "matter.fiduciary.email",
    label: "Petitioner/fiduciary email",
    fieldType: "text",
    required: false,
    reviewRequired: false,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_FIDUCIARY_RELATIONSHIP",
    estateHornetPath: "matter.fiduciary.relationship",
    label: "Fiduciary relationship",
    fieldType: "text",
    required: false,
    reviewRequired: true,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_ORIGINAL_WILL_AVAILABLE",
    estateHornetPath: "matter.originalWillAvailable",
    label: "Original will available",
    fieldType: "text",
    formatter: "yesNo",
    required: true,
    reviewRequired: true,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "Will dated",
    estateHornetPath: "matter.willDate",
    label: "Date of will",
    fieldType: "date",
    formatter: "date",
    required: false,
    reviewRequired: true,
    enabled: true,
    notes: "Confirmed from installed PC-200 AcroForm field inspection.",
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_CODICILS",
    estateHornetPath: "matter.codicils",
    label: "Codicils",
    fieldType: "text",
    formatter: "yesNo",
    required: false,
    reviewRequired: true,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_NAMED_EXECUTOR",
    estateHornetPath: "matter.namedExecutor",
    label: "Named executor",
    fieldType: "text",
    required: false,
    reviewRequired: true,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_BOND_WAIVED",
    estateHornetPath: "matter.bondWaived",
    label: "Bond waived",
    fieldType: "text",
    formatter: "yesNo",
    required: false,
    reviewRequired: true,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "Estimated vale of solely owned assets",
    estateHornetPath: "matter.assets.estimatedTotalValue",
    label: "Estimated value of solely owned assets",
    fieldType: "currency",
    formatter: "currency",
    required: false,
    reviewRequired: true,
    enabled: true,
    notes: "Confirmed from installed PC-200 AcroForm field inspection. Field label in PDF appears to contain original spelling.",
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_INTERESTED_PARTIES",
    estateHornetPath: "matter.people.interestedPartiesList",
    label: "Interested parties list",
    fieldType: "list",
    formatter: "multilineList",
    required: true,
    reviewRequired: true,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_HEIRS",
    estateHornetPath: "matter.people.heirsList",
    label: "Heirs list",
    fieldType: "list",
    formatter: "multilineList",
    required: false,
    reviewRequired: true,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_BENEFICIARIES",
    estateHornetPath: "matter.people.beneficiariesList",
    label: "Beneficiaries list",
    fieldType: "list",
    formatter: "multilineList",
    required: false,
    reviewRequired: true,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_PREPARER",
    estateHornetPath: "matter.assignedParalegal",
    label: "Attorney/paralegal/contact",
    fieldType: "text",
    required: false,
    reviewRequired: true,
    enabled: false,
    notes: inspectionNote,
  },
  {
    pdfFieldName: "UPDATE_AFTER_INSPECTION_DATE_PREPARED",
    estateHornetPath: "today",
    label: "Date prepared",
    fieldType: "date",
    formatter: "date",
    required: false,
    reviewRequired: false,
    enabled: false,
    notes: inspectionNote,
  },
];
